openapi: 3.0.0
info:
  description: ''
  version: 0.0.1
  title: Rooms API
  termsOfService: 'https://windingtree.com/terms'
  contact:
    email: hi@windingtree.com
  license:
    name: MIT
    url: 'https://github.com/windingtree/rooms/blob/master/LICENSE'
servers:
  - url: 'https://staging.rooms.windingtree.com/api'
security:
  - bearerAuth: []
paths:
  /ping:
    get:
      responses:
        '200':
          description: OK
  /health:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
components:
  parameters: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    HealthResponse:
      type: object
      properties:
        db:
          type: string
      required:
        - db
